version: '3.2'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: 'filebrowser'
    restart: always
    volumes:
      - ./data:/srv
      - ./filebrowser.db:/database.db
      - ./.filebrowser.json:/.filebrowser.json
    tty: true
    ports:
      - 18003:80

  aria2:
    image: xujinkai/aria2-with-webui
    container_name: 'aria2'
    restart: always
    volumes:
      - ./data:/data
      - ./ariaConf:/conf
    tty: true
    ports:
      - 18000:6800
      - 18001:80
      - 18002:8080
    environment:
      - SECRET=123456a131
  
  frpc:
    image: oldiy/frpc
    container_name: 'frpc'
    restart: always
    volumes:
      - ./frpc.ini:/frp/frpc.ini
    tty: true
    network_mode: host