version: '3.2'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: 'filebrowser'
    restart: always
    volumes:
      - /home/nd/data:/srv
      - /home/nd/filebrowser.db:/database.db
      - /home/nd/filebrowser.json:/.filebrowser.json
    tty: true
    ports:
      - 8001:80

  aria2:
    image: xujinkai/aria2-with-webui
    container_name: 'aria2'
    restart: always
    volumes:
      - /home/nd/data:/data
      - /home/nd/ariaConf:/conf
    tty: true
    ports:
      - 6800:6800
      - 6880:80
      - 6888:8080
    environment:
      - SECRET=123456a131
  