version: '3.2'
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: 'filebrowser'
    restart: always
    volumes:
      - ./data:/srv
      - ./filebrowser.db:/database.db
      - ./.filebrowser.json:/.filebrowser.json
    tty: true
    ports:
      - 8001:80

  aria2:
    image: xujinkai/aria2-with-webui
    container_name: 'aria2'
    restart: always
    volumes:
      - ./data:/data
      - ./ariaConf:/conf
    tty: true
    ports:
      - 6800:6800
      - 6880:80
      - 6888:8080
    environment:
      - SECRET=123456a131
  